# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\ DEVELOPMENT ENVIRONMENT \\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
version: "3.9"
services:
  # ------------------------------------------------------------
  # Node - Backend
  # ------------------------------------------------------------
  backend:
    build:
      context: packages/backend
    hostname: backend_dev
    volumes:
      - ./packages/backend/:/home/node/app
    environment:
      NODE_ENV: ${NODE_ENV}
    command:
      - sh
      - -c
      - npm ci && npm run start:dev
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - transcendence-network
    restart: unless-stopped

  # ------------------------------------------------------------
  # PostreSQL - Database
  # ------------------------------------------------------------
  db:
    image: postgres:12-alpine
    hostname: postgres-db_dev
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - transcendence-network
    restart: always

volumes:
  pgdata:

networks:
  transcendence-network:
    driver: bridge
