version: "3.9"

services:
  backend:
    container_name: backend
    env_file: .env
    build:
      context: packages/backend
      target: ${DEPLOYMENT_ENV}
    volumes:
      - ./packages/backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${BACKEND_PORT}:3000
      - 9229:9229
    networks:
      - bp-network
    # depends_on:
    #   - bp-pg-db
    # links:
    #   - bp-pg-db
    restart: always

  # frontend:
  #   container_name: frontend
  #   env_file: .env
  #   build:
  #     context: ./packages/frontend
  #     target: ${DEPLOYMENT_ENV}
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./packages/frontend/src:/usr/src/app/src
  #   ports:
  #     - ${FRONTEND_PORT}:${FRONTEND_PORT}
  #   networks:
  #     - bp-network
  #   restart: always

  # bp-pg-db:
  #   image: postgres:12-alpine
  #   container_name: bp-pg-db
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     PGDATA: /var/lib/postgresql/data
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_DB: ${DB_NAME}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - ${DB_PORT}:${DB_PORT}
  #   networks:
  #     - bp-network
  #   restart: always

  # pgadmin-portal:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin-portal
  #   env_file:
  #     - .env
  #   environment:
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #   volumes:
  #     - pgadmin:/root/.pgadmin
  #   ports:
  #     - ${PGADMIN_PORT}:80
  #   networks:
  #     - bp-network
  #   depends_on:
  #     - bp-pg-db
  #   restart: always

volumes:
  pgdata:
  pgadmin:
  node_modules:

networks:
  bp-network:
    driver: bridge
